import axios from 'axios';

const endpoint = 'https://YOUR_NGROK_URL/charge';

const pay = async (amount, description, access_token, token_id) => {
    const data = {
    'amount': amount,
    'description': description,
    'access_token': access_token,
    'token_id': token_id // the token generated by Stripe
    };

    const headers = {
    'Content-Type': 'application/json',
    };

    try {
        let response_data = await axios.post(endpoint, data, { headers });
        return true;
    } catch (e) {
        console.log('server error: ', e);
    }

    return false;      
}

export default pay;